name: Convert modpack text

on:
  push:
    paths:
      - modpack-text-md.md

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert md to one-line txt with \n
        run: |
          sed ':a;N;$!ba;s/\n/\\n/g' modpack-text-md.md > modpack-text.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@users.noreply.github.com"
          git add modpack-text.txt
          git commit -m "Auto-convert modpack-text-md.md to modpack-text.txt" || exit 0
          git push
